#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyroute2
Version  : 0.5.5
Release  : 25
URL      : https://files.pythonhosted.org/packages/b0/f2/8874ee4a8abb5d5e5b96b4f2f31391c860fe2267bce3e58bcead335e02bf/pyroute2-0.5.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/f2/8874ee4a8abb5d5e5b96b4f2f31391c860fe2267bce3e58bcead335e02bf/pyroute2-0.5.5.tar.gz
Summary  : Python Netlink library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 GPL-2.0+
Requires: pyroute2-bin = %{version}-%{release}
Requires: pyroute2-license = %{version}-%{release}
Requires: pyroute2-python = %{version}-%{release}
Requires: pyroute2-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Pyroute2
========
Pyroute2 is a pure Python **netlink** library. It requires only Python stdlib,
no 3rd party libraries. The library was started as an RTNL protocol
implementation, so the name is **pyroute2**, but now it supports many netlink
protocols. Some supported netlink families and protocols:

%package bin
Summary: bin components for the pyroute2 package.
Group: Binaries
Requires: pyroute2-license = %{version}-%{release}

%description bin
bin components for the pyroute2 package.


%package license
Summary: license components for the pyroute2 package.
Group: Default

%description license
license components for the pyroute2 package.


%package python
Summary: python components for the pyroute2 package.
Group: Default
Requires: pyroute2-python3 = %{version}-%{release}

%description python
python components for the pyroute2 package.


%package python3
Summary: python3 components for the pyroute2 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyroute2 package.


%prep
%setup -q -n pyroute2-0.5.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553958991
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyroute2
cp LICENSE.Apache.v2 %{buildroot}/usr/share/package-licenses/pyroute2/LICENSE.Apache.v2
cp LICENSE.GPL.v2 %{buildroot}/usr/share/package-licenses/pyroute2/LICENSE.GPL.v2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyroute2-cli
/usr/bin/ss2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyroute2/LICENSE.Apache.v2
/usr/share/package-licenses/pyroute2/LICENSE.GPL.v2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
