#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyroute2
Version  : 0.5.3
Release  : 22
URL      : https://files.pythonhosted.org/packages/19/1c/fc2efd9dfa5c1f7f713dbfee621365ad01f7b7ec0a6908e444f08bfd5873/pyroute2-0.5.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/19/1c/fc2efd9dfa5c1f7f713dbfee621365ad01f7b7ec0a6908e444f08bfd5873/pyroute2-0.5.3.tar.gz
Summary  : Python Netlink library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 GPL-2.0+
Requires: pyroute2-bin
Requires: pyroute2-python3
Requires: pyroute2-license
Requires: pyroute2-python
BuildRequires : buildreq-distutils3

%description
========
        
        Pyroute2 is a pure Python **netlink** library. It requires only Python stdlib,
        no 3rd party libraries. The library was started as an RTNL protocol
        implementation, so the name is **pyroute2**, but now it supports many netlink

%package bin
Summary: bin components for the pyroute2 package.
Group: Binaries
Requires: pyroute2-license = %{version}-%{release}

%description bin
bin components for the pyroute2 package.


%package license
Summary: license components for the pyroute2 package.
Group: Default

%description license
license components for the pyroute2 package.


%package python
Summary: python components for the pyroute2 package.
Group: Default
Requires: pyroute2-python3 = %{version}-%{release}

%description python
python components for the pyroute2 package.


%package python3
Summary: python3 components for the pyroute2 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyroute2 package.


%prep
%setup -q -n pyroute2-0.5.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538329967
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pyroute2
cp LICENSE.Apache.v2 %{buildroot}/usr/share/doc/pyroute2/LICENSE.Apache.v2
cp LICENSE.GPL.v2 %{buildroot}/usr/share/doc/pyroute2/LICENSE.GPL.v2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ss2

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/pyroute2/LICENSE.Apache.v2
/usr/share/doc/pyroute2/LICENSE.GPL.v2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
